version: '3'
services:
  shortendUrlBackend: # service name
    container_name: shortend-url-backend # container name
    image: shortend-url-backend:1.0 # image name:tag
    build: . # build source file location
    restart: always # restart the container if it crashes for any reason
    ports:
      - "5000:5000" # OS port : Docker port
    env_file:
      - .env